trigger:
  - master

variables:
  azureSubscriptionEndpoint: $(service-connection-name)
  azureContainerRegistry: $(container-registry-host)
  registryName: $(azureContainerRegistry)/$(Build.Repository.Name)
  imageTag: $(registryName):$(Build.BuildId)
  appName: $(app-name)

# Build and push image for Container1

- stage: BuildImage
  displayName: 'Build'
  jobs:
    - job: build_and_push_image
      steps:
      - script: |
          echo '##vso[task.setvariable variable=buildSha]'$(git rev-parse --short HEAD)''
          echo 'buildSha set to $(buildSha)'
        displayName: Get build git sha
      - script: docker build --tag $(imageTag)-$(buildSha) Docker-Manifest/Cointainer1
        displayName: 'Docker: Build and tag image'

      # Use the task to avoid embedding credentials in pipeline
      - task: Docker@1
        displayName: 'Docker: login ACR'
        inputs:
          command: login
          azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
          azureContainerRegistry: $(azureContainerRegistry)

      - script: docker push $(imageTag)-$(buildSha)
        displayName: 'Docker: Push image'

      - script: docker logout $(azureContainerRegistry)
        displayName: 'Docker: logout ACR'