apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
      - name: container1
        image: defaultacrname.azurecr.io/container1:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
