apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
      - name: container1
        image: spartha1995/container-services:containerservice1
        ports:
        - containerPort: 80
