apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container1
        image: defaultacrname.azurecr.io/container2:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
